CONFIG:
  DIRECTORY: source/config

OUTPUT:
  DIRECTORY: output

DATA:
  RAW_DIRECTORY: artifacts/data/raw
  INTERIM_DIRECTORY: artifacts/data/interim
  PROCESSED_DIRECTORY: artifacts/data/processed
  EXTERNAL_DIRECTORY: artifacts/data/external

NOTEBOOKS:
  DIRECTORY: source/notebooks

MLFLOW:
  URI: http://mlflow_server:1235
  EXPERIMENT_NAME: credit
  MODEL_NAME: credit_model
