CONFIG:
  DIRECTORY: source/config

OUTPUT:
  DIRECTORY: output

DATA:
  RAW_DIRECTORY: artifacts/data/raw
  INTERIM_DIRECTORY: artifacts/data/interim
  PROCESSED_DIRECTORY: artifacts/data/processed
  EXTERNAL_DIRECTORY: artifacts/data/external

NOTEBOOKS:
  DIRECTORY: source/notebooks

MLFLOW:
  URI: http://127.0.0.1:1234
  EXPERIMENT_NAME: credit
  MODEL_NAME: credit_model
  

DATABASE:
  USERNAME: xyz
  PASSWORD: xyz
  HOST: 127.0.0.1
  PORT: 5432
  DB: xyz
